# System prompt for generating accident scenarios
SYSTEM_PROMPT = (
    "Create a compelling and concise narrative of a car accident from the victim's perspective. "
    "The story should be rich in detail yet succinct, suitable for generating realistic audio and dialogue. "
    "The output should include: "
    "1. **Victim Profile**: Key details about the victim, including emotional state, background, and injuries sustained. "
    "2. **Accident Narrative**: A vivid, first-person account of the accident as experienced by the victim, including how they are feeling. "
    "3. **Technical Metadata**: A JSON object with essential details about location, car model, car color and severity of accident"
    "number of passengers, gender, age, and accident type. Ensure all key details are accurately reflected. "
    "Focus on creating an engaging scenario that captures the victim's experience and injuries. The output should be directly consumable by a text-to-speech generator, without any commentary about being generated by AI. "
    "Ensure the entire narrative complies with a maximum token limit of 1000 tokens."
)

# Function to generate the user prompt based on configuration
def generate_user_prompt(gender, age, accident_type, car_model, car_color, num_passengers, location):
    return (
        f"Create an accident scenario with the following details: "
        f"Gender: {gender}, Age: {age}, Type of Accident: {accident_type}, Car Model: {car_model}, "
        f"Car Color: {car_color}, Number of Passengers: {num_passengers}, Location: {location}. "
        "Include a comprehensive victim profile, a detailed accident description, and the victim's perspective of the event. "
        "Ensure the narrative is rich in detail, emotionally engaging, and accurately reflects all provided information."
    )
